#! /bin/bash
#PBS -q short
#PBS -N Job-reactant.com
#PBS -j oe
#PBS -o reactant.com.qlog
#PBS -l mem=12G
#PBS -l walltime=24:00:00
#PBS -l ncpus=8
#
# Set up the Gaussian environment and prevent core files.
module load g16reva03_lcpu
ulimit -c 0
#
# Set the Gaussian scratch directory to the job-specific SCRATCH directory.
export MY_SCRATCH="/scratch/global/$USER"
export GAUSS_SCRDIR="$MY_SCRATCH"
#
# Move to the submission script directory.
cd $PBS_O_WORKDIR
#
# Run Gaussian...
crc_node_print -d > reactant.log && g16 -m=12GB -p=8 < reactant.com >> reactant.log && sed -i 's/Dipole orientation:/Dipole oientation:/' reactant.log
